// <auto-generated />
using System;
using ManchiEco.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManchiEco.EntityFramework.Migrations
{
    [DbContext(typeof(ManchiEcoDbContext))]
    [Migration("20241110060057_PorcentajeVigente")]
    partial class PorcentajeVigente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ManchiEco.Domain.Entities.Ahorro", b =>
                {
                    b.Property<int>("AhorroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AhorroId"));

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("AhorroId");

                    b.ToTable("Ahorros", (string)null);
                });

            modelBuilder.Entity("ManchiEco.Domain.Entities.Cuota", b =>
                {
                    b.Property<int>("CuotaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CuotaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NroCuotas")
                        .HasColumnType("int");

                    b.Property<int>("TipoCuotaId")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("CuotaId");

                    b.ToTable("Cuotas", (string)null);
                });

            modelBuilder.Entity("ManchiEco.Domain.Entities.Gusto", b =>
                {
                    b.Property<int>("GustoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GustoId"));

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("GustoId");

                    b.ToTable("Gustos", (string)null);
                });

            modelBuilder.Entity("ManchiEco.Domain.Entities.Ingreso", b =>
                {
                    b.Property<int>("IngresoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngresoId"));

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("IngresoId");

                    b.ToTable("Ingresos", (string)null);
                });

            modelBuilder.Entity("ManchiEco.Domain.Entities.Porcentaje", b =>
                {
                    b.Property<int>("PorcentajeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PorcentajeID"));

                    b.Property<int>("Ahorro")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gustos")
                        .HasColumnType("int");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("PorcentajeID");

                    b.ToTable("Porcentajes", (string)null);
                });

            modelBuilder.Entity("ManchiEco.Domain.Entities.TipoCuota", b =>
                {
                    b.Property<int>("TipoCuotaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoCuotaId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoCuotaId");

                    b.ToTable("TipoCuotas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
